### ISSUE TITLE
color all rois

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#10]
Is there an easy way to get this figure with a legend using img_pipe? 
![image](https://cloud.githubusercontent.com/assets/844306/26661204/331000a2-4631-11e7-9821-53c99659b5c7.png)

**Comment by libertyh** [comment]
Not explicitly, but this is definitely doable with a combination of `patient.plot_brain()` with ROIs from `patient.get_rois()` made into meshes with `patient.make_roi_mesh()`.  You'd then get colors from the freesurfer lookup table (implemented as a dictionary: `import SupplementalFiles.FS_colorLUT as FS_colorLUT`).

**Comment by libertyh** [comment]
The easiest way is just to look at the lh.pial or rh.pial in Freeview, then load lh.aparc.annot or rh.aparc.annot as an annotation on top.  I'm going to close this issue and will make a comment later if this is implemented later.

**Comment by bendichter** [comment]
Ran into issue #11: I needed write access to SUBJECT_DIR to do this
