### ISSUE TITLE
freeCoG.make_rio_mesh() requires write access to SUBJECT_DIR

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#11]
which makes it unusable for me. I'm going to look into it and see if I can make some similar changes here so that I can use it.

**Comment by libertyh** [comment]
I fixed this-- now pass `save=False` to `make_roi_mesh()` when you make meshes and it will return the roi_mesh as a dictionary, e.g.

`mesh=patient.make_roi_mesh('lateralorbitofrontal',['lateralorbitofrontal'], save=False)`
`mesh['tri']`
`mesh['vert']`
`mesh,mlab=ctmr_gauss_plot(mesh['tri'],mesh['vert'])`
`mlab.show()`

If you still want these to save to the Meshes directory, the default is `save=True`.

See https://github.com/ChangLabUcsf/img_pipe/commit/cc7638969d52f7201a3b34e435ae65d1edb4a4e5
