### ISSUE TITLE
2d projection of warped electrode positions

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#23]
Is there any way to save 2D coordinates of warped electrodes onto a template brain? This was one of the features of my auto_2d_brain.m function.

**Comment by bendichter** [comment]
It is a feature I would need in order to move my project entirely away from matlab and onto `img_pipe`. It doesn't need to be within `freeCoG.auto_2d_brain` in `img_pipe`-- it could be a separate function.

**Comment by libertyh** [comment]
No, but I will add it. Just have to pass an `elecfile_prefix='TDT_elecs_all_warped'` (or whatever warped file) to `patient.get_elecs()`, and an argument for a `template` brain.  Doing that now.

**Comment by bendichter** [comment]
Great! I also need a 2d version of the template brain. I imagine that's also fairly simple..

**Comment by libertyh** [comment]
Yes, it would be made in the same way.

**Comment by libertyh** [comment]
Try something like this:
`import img_pipe`
`patient = img_pipe.freeCoG(subj='EC36', hem='lh')`
`brain_image, elecmatrix = patient.auto_2D_brain(azimuth=180, 
                                                    elecfile_prefix='TDT_elecs_all_warped', 
                                                    template='cvs_avg35_inMNI152', force=True)`

(you can also use your brain_file and elecs_2D_file if needed).  Note that this saves the 2D png in the cvs_avg35_inMNI152 directory by default so you don't have to save it over and over again in different subdirectories if you already have the image available.  However, the elecfiles are still saved to the subject's elecs directory (I know this isn't relevant for you if you can't write there, but fyi).
