### ISSUE TITLE
auto_2d_brain brain_file and no elecs_file

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#31]
In `auto_2d_brain`, if `brain_file` is a file and `force is False`, then the brain image is loaded from the file and `f` is never defined. If `elecs_2D_file` is not an existing file, `f` is required and an error will occur.

Possible solutions:
* If `brain_file` is defined and `force is False`, require user to also define `elecs_2D_file`. i.e. re-generate both or neither.
* Save `f.scene` somewhere and load it when you load from `brain_file`.
* Take away `brain_file` option, forcing the use of `self.plot_brain()`, which outputs `f`.
* Algorithmically determine scene parameters from `azimuth` and `elevation`.

I think the first solution would be the easiest to implement. I am going to implement this one and PR, because I need to move on, but if you would prefer a different solution feel free to ignore.

**Comment by libertyh** [comment]
Fixed with merge -- thanks!
